---
language: elixir
elixir:
  - '1.5.2'
otp_release:
  - '20.1'

sudo: false
dist: trusty

addons:
  chrome: stable
  postgresql: '9.6'

cache:
  yarn: true
  directories:
    - $TRAVIS_BUILD_DIR/backend/deps
    - $TRAVIS_BUILD_DIR/backend/_build

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - MIX_ENV=test

before_install:
  - sudo /etc/init.d/postgresql stop
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs 2>/dev/null)-pgdg main" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update -qq
  - sudo apt-get install -qq postgresql-10 postgresql-client-10
  - sudo cp /etc/postgresql/9.6/main/pg_hba.conf /etc/postgresql/10/main/pg_hba.conf
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
  - sudo /etc/init.d/postgresql restart
  - psql -c "CREATE ROLE travis WITH SUPERUSER LOGIN;" -U postgres
  - psql -c "CREATE DATABASE travis OWNER travis;" -U postgres

  - nvm install 9.4.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.4.0
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - cd $TRAVIS_BUILD_DIR/backend
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - mix ecto.create
  - cd $TRAVIS_BUILD_DIR/client
  - yarn install --non-interactive

script:
  - cd $TRAVIS_BUILD_DIR/client
  - yarn test
  - yarn lint:js
  - cd $TRAVIS_BUILD_DIR/backend
  - mix credo --strict
  - mix dialyzer
  - mix coveralls.travis
